# Generated by Django 5.2.5 on 2025-09-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10)),
            ],
        ),
    ]
