# Generated by Django 5.2.5 on 2025-09-08 17:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_and_incomes', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
